#####
### Project Babbage — Services for Local Development
#####
version: '3.8'
networks:
  babnet:
    ipam:
      config:
        - subnet: 172.20.0.0/23

services:

  ###
  ## Standard MetaNet Services
  ###

  # MiniScribe — lightweight local NanoStore
  miniscribe:
    image: us.gcr.io/computing-with-integrity/miniscribe
    ports:
      - "3104:3104"
    volumes:
     - ./data/miniscribe-data:/app/data
    environment:
      NODE_ENV: 'development'

  # The Bridgeport Connecticut Proxy
  connecticut:
    image: us.gcr.io/computing-with-integrity/connecticut
    ports:
      - "3103:3103"
    environment:
      HTTP_PORT: 3103
      PORT: 3103

  ###
  ## Bridgeport Derived Action Datasets
  ###

  # MongoDB
  bridgeport-mongo:
    image: mongo
    command: |
      bash -c "mongod --bind_ip_all --replSet rs0 --fork --syslog --port 3113 && mongo --port 3113 --eval \"if (!rs.status().ok) rs.initiate({_id : 'rs0', members : [{_id : 0, host : 'bridgeport-mongo:3113'}]})\" && mongo --port 3113 --eval \"while(true) {if (!rs.status().ok) break;sleep(1000)};\""
    hostname: "bridgeport-mongo"
    ports:
      - 3113:27017
    volumes:
     - ./data/bridgeport-mongo-data:/data/db

  ###
  ## System Bridges (Used by the kernel, do not modify)
  ###

  # UMP — User Management Protocol
  ump-reader:
    hostname: "reader-1h48c3wg1ycgpt7tx61phzh8lx6v5tvukl"
    image: us.gcr.io/computing-with-integrity/bitquery-mongo-reader
    environment:
      BRIDGE: 'eyJpZCI6IjFINDhDM3dnMVljZ3BUN1R4NjFQSHpIOEx4NnY1dFZVS0wifQ=='
      PORT: 80
      MONGODB_READ_CREDS: 'bW9uZ29kYjovL2JyaWRnZXBvcnQtbW9uZ286MzExMy9icmlkZ2VfMUg0OEMzd2cxWWNncFQ3VHg2MVBIekg4THg2djV0VlVLTA=='
      MONGODB_DATABASE: 'bridge_1H48C3wg1YcgpT7Tx61PHzH8Lx6v5tVUKL'
      DEFAULT_QUERY: '{"v": 3,"q": {"collection": "users", "find": {}}}'
      DEFAULT_SOCKET: '{"v": 3,"q": {"find": {}}}'
  ump-transformer:
    hostname: "transformer-1h48c3wg1ycgpt7tx61phzh8lx6v5tvukl"
    image: us.gcr.io/computing-with-integrity/ump-transformer
    environment:
      PORT: 80
      MONGODB_WRITE_CREDS: 'mongodb://bridgeport-mongo:3113/bridge_1H48C3wg1YcgpT7Tx61PHzH8Lx6v5tVUKL'
      MONGODB_DATABASE: 'bridge_1H48C3wg1YcgpT7Tx61PHzH8Lx6v5tVUKL'

  # DPACP — DNS Protocol Access Control Protocol
  dpacp-reader:
    hostname: "reader-1hceb1o8bahkfe1degfn9kfuvdmjw2creg"
    image: us.gcr.io/computing-with-integrity/bitquery-mongo-reader
    environment:
      BRIDGE: 'eyJpZCI6IjFIY2VCMW84YmFoa2ZlMWRFZ0ZOOWtGdVZEbUp3MkNSRWcifQ=='
      PORT: 80
      MONGODB_READ_CREDS: 'bW9uZ29kYjovL2JyaWRnZXBvcnQtbW9uZ286MzExMy9icmlkZ2VfMUhjZUIxbzhiYWhrZmUxZEVnRk45a0Z1VkRtSncyQ1JFZw=='
      MONGODB_DATABASE: 'bridge_1HceB1o8bahkfe1dEgFN9kFuVDmJw2CREg'
  dpacp-transformer:
    hostname: "transformer-1hceb1o8bahkfe1degfn9kfuvdmjw2creg"
    image: us.gcr.io/computing-with-integrity/dpacp-transformer
    environment:
      PORT: 80
      MONGODB_WRITE_CREDS: 'mongodb://bridgeport-mongo:3113/bridge_1HceB1o8bahkfe1dEgFN9kFuVDmJw2CREg'
      MONGODB_DATABASE: 'bridge_1HceB1o8bahkfe1dEgFN9kFuVDmJw2CREg'

  # DSAP — DNS Spending Authorization Protocol
  dsap-reader:
    hostname: "reader-1lr6iemvft5ftep1n451c2oa3ze3jft29i"
    image: us.gcr.io/computing-with-integrity/bitquery-mongo-reader
    environment:
      BRIDGE: 'eyJpZCI6IjFMcjZpZU12ZlQ1ZlRFcDFONDUxQzJvQTN6RTNKRnQyOWkifQ=='
      PORT: 80
      MONGODB_READ_CREDS: 'bW9uZ29kYjovL2JyaWRnZXBvcnQtbW9uZ286MzExMy9icmlkZ2VfMUxyNmllTXZmVDVmVEVwMU40NTFDMm9BM3pFM0pGdDI5aQ=='
      MONGODB_DATABASE: 'bridge_1Lr6ieMvfT5fTEp1N451C2oA3zE3JFt29i'
  dsap-transformer:
    hostname: "transformer-1lr6iemvft5ftep1n451c2oa3ze3jft29i"
    image: us.gcr.io/computing-with-integrity/dsap-transformer
    environment:
      PORT: 80
      MONGODB_WRITE_CREDS: 'mongodb://bridgeport-mongo:3113/bridge_1Lr6ieMvfT5fTEp1N451C2oA3zE3JFt29i'
      MONGODB_DATABASE: 'bridge_1Lr6ieMvfT5fTEp1N451C2oA3zE3JFt29i'

  ###
  ## Debugging Tools — Uncomment when needed
  ###
  
  # Mongo Express — web-based MongoDB database viewer
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: bridgeport-mongo
      ME_CONFIG_MONGODB_PORT: 3113
    depends_on:
      - bridgeport-mongo

  ## PHPMyAdmin — Web-based SQL database viewer
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #   - dojo-mysql
  #   environment:
  #     PMA_HOST: dojo-mysql
  #     PMA_PORT: 3112
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #   - 8090:80
  #   networks:
  #   - babnet

  ###
  ## User-defined Bridges and Services — Extend to support your application
  ###

  # tsp-bridge - Tempo Song Protocol Bridge
  tsp-reader:
    hostname: "reader-1lqtkkk7c1tn3ucrfsp8sqgjwtzgskze36"
    build: '../tsp-bridge/reader'
    environment:
      BRIDGE: 'eyJpZCI6IjFMUXRLS0s3YzFUTjNVY1Jmc3A4U3FHald0ekdza3plMzYifQ=='
      PORT: 80
      MONGODB_READ_CREDS: 'bW9uZ29kYjovL2JyaWRnZXBvcnQtbW9uZ286MzExMy9icmlkZ2VfMUxRdEtLSzdjMVROM1VjUmZzcDhTcUdqV3R6R3NremUzNg=='
      MONGODB_DATABASE: 'bridge_1LQtKKK7c1TN3UcRfsp8SqGjWtzGskze36'
  tsp-transformer:
    hostname: "transformer-1lqtkkk7c1tn3ucrfsp8sqgjwtzgskze36"
    build: '../tsp-bridge/transformer'
    command: node --inspect=0.0.0.0 ./server.js
    ports:
      - 9229:9229
    environment:
      PORT: 80
      MONGODB_WRITE_CREDS: 'mongodb://bridgeport-mongo:3113/bridge_1LQtKKK7c1TN3UcRfsp8SqGjWtzGskze36'
      MONGODB_DATABASE: 'bridge_1LQtKKK7c1TN3UcRfsp8SqGjWtzGskze36'

  # tempo-key-server
  tempo-key-server:
      platform: linux/x86_64
      hostname: 'tempo-key-server'
      build: '../tempo-key-server'
      restart: always
      volumes:
      - './data/tempo-key-server-mysql-data:/var/lib/mysql'
      ports:
      - 8080:8080
      environment:
        NODE_ENV: development
        HTTP_PORT: 8080
        DATABASE_FILENAME: './data/database.sqlite'
        KNEX_DB_CONNECTION: '{"port":"3306","host":"127.0.0.1","database":"tempo-key-server","user":"","password":""}'
        KNEX_DB_CLIENT: mysql
        MIGRATE_KEY: my-grate-key
        SERVER_PRIVATE_KEY: '6dcc124be5f382be631d49ba12f61adbce33a5ac14f6ddee12de25272f943f8b'
        HOSTING_DOMAIN: 'http://localhost:8080'
