apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tempo-key-server-tls
  labels:
    app.kubernetes.io/name: tempo-key-server
    app.kubernetes.io/component: tls
spec:
  secretName: tempo-key-server-tls
  dnsNames: []
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-nginx
