apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempo-key-server
  labels:
    app.kubernetes.io/name: tempo-key-server
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
    nginx.ingress.kubernetes.io/session-cookie-name: "tempo-key-server"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Lax"
spec:
  ingressClassName: nginx
  tls:
    - hosts: []
      secretName: tempo-key-server-tls
  rules: []
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tempo-key-server-tls
  labels:
    app.kubernetes.io/name: tempo-key-server
    app.kubernetes.io/component: tls
spec:
  secretName: tempo-key-server-tls
  dnsNames: []
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-nginx
