apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo-key-server-prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: tempo-key-server
    newName: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/tempo-key-server
    newTag: local

patches:
  - target:
      kind: Ingress
      name: tempo-key-server
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - tempo-keyserver.babbage.systems
      - op: replace
        path: /spec/rules
        value:
          - host: tempo-keyserver.babbage.systems
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: tempo-key-server
                      port:
                        number: 8081
  - target:
      kind: Certificate
      name: tempo-key-server-tls
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - tempo-keyserver.babbage.systems
